### ISSUE TITLE
Node >=7.6.0 Requirement

### ISSUE THREAD

**Issue by westy92** [cedx/gulp-david#14]
As far as I can tell, [Node >=7.6.0 is required](https://github.com/cedx/gulp-david/blob/master/package.json#L34).  I find this concerning, since the latest Node LTS release is 6.10.0.

I guess I will have to stick with gulp-david v4.x even though I'm running the latest LTS version of Node. :disappointed:

**Comment by cedx** [comment]
That's right: I like using the latest features from every technology I use (Node.js, PHP or whatever).

But by looking more closely at the changelog and the code of each tag, you will realize that ultimately little has changed. I'm following the semantic versionning, so I must increment the major version number with every breaking change, however small it may be.

The big change is the use of async/await functions instead of Promises, but v4, v5 and v6 are merely the same (e.g. changes are only internal).

**Comment by westy92** [comment]
I understand wanting to use the latest language features, which is why many people use Babel, TypeScript, etc.

However, it is very rare to drop support for the latest LTS release.  I could, however, see this as acceptable if you were planning on backporting all bugfixes to your 4.x version.  Do you plan to do that?

**Comment by cedx** [comment]
Sure. I will release in the next few days a new v4 integrating the latest bug fixes and dependency updates.

**Comment by cedx** [comment]
"Fixed" in the released version 4.1.0.

I will try try to keep the "release/v4.x" branch in sync with the latest package updates, but do not hesitate to remind me if I forget.
